import type { NextPage } from 'next';
import Head from 'next/head';
import AdminForm from 'components/admin-form';
import { Formik, Form, Field, FormikHelpers } from 'formik';



const Dashboard: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AdminForm />
        </div>

    );
    };

    export default Dashboard;