import type { NextPage } from 'next';
import Head from 'next/head';
import AdminForm from 'components/citizen-form';
import { Formik, Form, Field, FormikHelpers } from 'formik';
import styles from '/components/stdColors.module.css'



const Dashboard: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Night assist admin</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <style jsx global>{`
                    body {
                    background-color: #E1ECFD;
                    margin: 0;
              
                    }
                `}</style>
      <main>
            <AdminForm />
            </main>

        </div>

    );
    };

    export default Dashboard;